//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTableSet
    {
        public int Id { get; set; }
        public string Quantity { get; set; }
        public string Description { get; set; }
    }
}
